CREATE TABLE "action_log" (
	"seq" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "action_log_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"actor_id" text,
	"actor_role_id" text,
	"action_type" text NOT NULL,
	"entity" text,
	"entity_id" text,
	"document_id" text,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"occurred_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "code_items" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"table_key" text NOT NULL,
	"value" text NOT NULL,
	"label" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"custom_fields" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"archived_at" timestamp,
	"archived_by" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "code_items_table_value_key" UNIQUE("table_key","value")
);
--> statement-breakpoint
CREATE TABLE "roles" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"is_seed" boolean DEFAULT false NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"custom_fields" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"archived_at" timestamp,
	"archived_by" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "roles_name_unique" UNIQUE("name")
);
--> statement-breakpoint
INSERT INTO "roles" ("id", "name", "is_seed", "sort_order") VALUES
	('role-ceo', '대표', true, 0),
	('role-division-head', '본부 책임자', true, 1),
	('role-team-lead', '팀장', true, 2),
	('role-pm', '기획 PM', true, 3),
	('role-sysadmin', '시스템 관리자', true, 4)
ON CONFLICT ("id") DO NOTHING;
--> statement-breakpoint
CREATE TABLE "permission_matrix" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"role_id" text NOT NULL,
	"menu" text NOT NULL,
	"action" text NOT NULL,
	"allowed" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"updated_by" text,
	CONSTRAINT "permission_matrix_role_menu_action_key" UNIQUE("role_id","menu","action")
);
--> statement-breakpoint
CREATE TABLE "visibility_matrix" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"role_id" text NOT NULL,
	"info_item" text NOT NULL,
	"visible" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"updated_by" text,
	CONSTRAINT "visibility_matrix_role_item_key" UNIQUE("role_id","info_item")
);
--> statement-breakpoint
SET LOCAL lock_timeout = '1s';
SET LOCAL statement_timeout = '5s';
--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "role_id" text;--> statement-breakpoint
ALTER TABLE "action_log" ADD CONSTRAINT "action_log_actor_id_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "permission_matrix" ADD CONSTRAINT "permission_matrix_role_id_roles_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "visibility_matrix" ADD CONSTRAINT "visibility_matrix_role_id_roles_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "action_log_actor_occurred_idx" ON "action_log" USING btree ("actor_id","occurred_at");--> statement-breakpoint
CREATE INDEX "action_log_type_occurred_idx" ON "action_log" USING btree ("action_type","occurred_at");--> statement-breakpoint
CREATE INDEX "action_log_document_idx" ON "action_log" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "code_items_table_sort_idx" ON "code_items" USING btree ("table_key","sort_order","value");--> statement-breakpoint
-- users는 이 마이그레이션 이전부터 있던 표라 permission_matrix/visibility_matrix
-- FK(방금 만든 빈 표에 거는 FK)와 달리 기존 행 스캔 우려가 있다 — NOT VALID로
-- 제약만 빠르게 걸고(신규/변경 행은 즉시 강제된다), 검증(VALIDATE CONSTRAINT)은
-- 같은 트랜잭션에서 하면 의미가 없어(squawk constraint-missing-not-valid 실측 —
-- "같은 트랜잭션에서 NOT VALID+VALIDATE를 쓰면 검증 중 모든 읽기가 막힌다")
-- 0004로 분리한다.
ALTER TABLE "users" ADD CONSTRAINT "users_role_id_roles_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE no action ON UPDATE no action NOT VALID;
--> statement-breakpoint
UPDATE "users" SET "role_id" = 'role-sysadmin' WHERE "is_admin" = true AND "role_id" IS NULL;
--> statement-breakpoint
UPDATE "users" SET "role_id" = 'role-pm' WHERE "is_admin" = false AND "role_id" IS NULL;
