-- Phase 04.2 — 알림 원장·tick 실행 기록. 머지 직전 origin/main 머지 → 이 페이즈의 마이그레이션·스냅숏·journal 항목 삭제 → pnpm db:generate 재실행. 번호나 _journal.json을 손으로 고치지 않는다.
SET LOCAL lock_timeout = '1s';
SET LOCAL statement_timeout = '5s';
--> statement-breakpoint
CREATE TABLE "notification_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notification_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"condition_kind" text NOT NULL,
	"entity" text NOT NULL,
	"entity_id" text NOT NULL,
	"recipient_id" text NOT NULL,
	"round" integer DEFAULT 1 NOT NULL,
	"reference_date" date NOT NULL,
	"message" text NOT NULL,
	"created_at" timestamp (3) DEFAULT now() NOT NULL,
	"read_at" timestamp,
	"email_status" text DEFAULT 'pending' NOT NULL,
	"email_attempted_at" timestamp,
	CONSTRAINT "notification_log_dedup_key" UNIQUE("condition_kind","entity","entity_id","recipient_id","round"),
	CONSTRAINT "notification_log_email_status_check" CHECK ("notification_log"."email_status" in ('pending', 'sending', 'sent', 'failed', 'unknown', 'skipped_no_smtp'))
);
--> statement-breakpoint
CREATE TABLE "notify_tick_runs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notify_tick_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"started_at" timestamp NOT NULL,
	"finished_at" timestamp NOT NULL,
	"kst_date" date NOT NULL,
	"business_day" boolean NOT NULL,
	"sent" integer DEFAULT 0 NOT NULL,
	"skipped" integer DEFAULT 0 NOT NULL,
	"remaining" integer DEFAULT 0 NOT NULL,
	"email_claimed" integer DEFAULT 0 NOT NULL,
	"email_sent" integer DEFAULT 0 NOT NULL,
	"email_failed" integer DEFAULT 0 NOT NULL,
	"email_unknown" integer DEFAULT 0 NOT NULL,
	"email_finished_at" timestamp,
	"incomplete_recipient_ids" text[] DEFAULT '{}'::text[] NOT NULL,
	"evaluation_failed" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
ALTER TABLE "notification_log" ADD CONSTRAINT "notification_log_recipient_id_users_id_fk" FOREIGN KEY ("recipient_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "notification_log_recipient_created_idx" ON "notification_log" USING btree ("recipient_id","created_at","id");