CREATE TABLE "restore_rehearsals" (
	"seq" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "restore_rehearsals_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"source" text NOT NULL,
	"succeeded" boolean NOT NULL,
	"failed_stage" text,
	"backup_id" text,
	"started_at" timestamp with time zone NOT NULL,
	"finished_at" timestamp with time zone NOT NULL,
	"run_url" text,
	"run_key" text NOT NULL,
	CONSTRAINT "restore_rehearsals_run_key_unique" UNIQUE("run_key"),
	CONSTRAINT "restore_rehearsals_source_check" CHECK ("restore_rehearsals"."source" in ('staging', 'production')),
	CONSTRAINT "restore_rehearsals_stage_check" CHECK (("restore_rehearsals"."succeeded" and "restore_rehearsals"."failed_stage" is null) or (not "restore_rehearsals"."succeeded" and "restore_rehearsals"."failed_stage" is not null and "restore_rehearsals"."failed_stage" in ('restore', 'verify', 'cleanup'))),
	CONSTRAINT "restore_rehearsals_failed_run_url_check" CHECK ("restore_rehearsals"."succeeded" or "restore_rehearsals"."run_url" is not null)
);
