-- Phase 04.4 — 복원 리허설 기록 표 · users.first_login_at. 머지 직전 origin/main 머지 → 이 페이즈의 마이그레이션·스냅숏·journal 항목 삭제 → pnpm db:generate 재실행. 번호나 _journal.json을 손으로 고치지 않는다.
SET LOCAL lock_timeout = '1s';
SET LOCAL statement_timeout = '5s';
--> statement-breakpoint
CREATE TABLE "restore_rehearsals" (
	"seq" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "restore_rehearsals_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"source" text NOT NULL,
	"succeeded" boolean NOT NULL,
	"failed_stage" text,
	"backup_id" text,
	"started_at" timestamp with time zone NOT NULL,
	"finished_at" timestamp with time zone NOT NULL,
	"run_url" text,
	"run_key" text NOT NULL,
	CONSTRAINT "restore_rehearsals_run_key_unique" UNIQUE("run_key"),
	CONSTRAINT "restore_rehearsals_source_check" CHECK ("restore_rehearsals"."source" in ('staging', 'production')),
	CONSTRAINT "restore_rehearsals_stage_check" CHECK (("restore_rehearsals"."succeeded" and "restore_rehearsals"."failed_stage" is null) or (not "restore_rehearsals"."succeeded" and "restore_rehearsals"."failed_stage" is not null and "restore_rehearsals"."failed_stage" in ('restore', 'verify', 'cleanup'))),
	CONSTRAINT "restore_rehearsals_failed_run_url_check" CHECK ("restore_rehearsals"."succeeded" or "restore_rehearsals"."run_url" is not null)
);
--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "first_login_at" timestamp;--> statement-breakpoint
-- 04.4 D8-07 first_login_at backfill
-- 기존 사용자: action_log login 행(pruned_at 무관)과 login_attempts 성공(이메일 대소문자 무관) 중 더 이른 시각.
UPDATE "users" AS u
SET "first_login_at" = least(
  (SELECT min(a."occurred_at") FROM "action_log" AS a WHERE a."action_type" = 'login' AND a."actor_id" = u."id"),
  (SELECT min(l."attempted_at") FROM "login_attempts" AS l WHERE l."success" = true AND l."email" = lower(u."email"))
)
WHERE u."first_login_at" IS NULL;--> statement-breakpoint
-- 기록이 없어도 임시 비밀번호가 아니면 로그인해 바꾼 사람이다 — 실행 시각으로 채운다. 그 밖은 NULL로 둔다.
UPDATE "users" SET "first_login_at" = now() WHERE "first_login_at" IS NULL AND "password_is_temporary" = false;
